class Districts{
  List<String> district_list = [
    "Mardan",
    "Swabi",
    "Charsadda",
    "Nowshera",
    "Peshawar",
    "Khyber",
    "Mohmand",
    "Dera Ismail Khan",
    "Tank",
    "Lower South Waziristan",
    "Upper South Waziristan",
    "Abbottabad",
    "Allai",
    "Battagram",
    "Haripur",
    "Kolai Palas",
    "Upper Kohistan",
    "Lower Kohistan",
    "Mansehra",
    "Torghar",
    "Hangu",
    "Ka rak",
    "Kohat",
    "Kurram",
    "Orakzai",
    "Baiaur",
    "Buner",
    "Central Dir",
    "Lower Chitral",
    "Lower Dir",
    "Malakand",
    "Shangla",
    "Swat",
    "Upper Dir",
    "Upper Chitral"
  ];
}